export const labels = {
  common: {
    save: "Enregistrer",
    cancel: "Annuler",
    delete: "Supprimer",
    edit: "Modifier",
    close: "Fermer",
    confirm: "Confirmer",
    retry: "Réessayer",
    loading: "Chargement...",
  },
  auth: {
    login: "Se connecter",
    logout: "Se déconnecter",
    signup: "Créer un compte",
    forgotPassword: "Mot de passe oublié ?",
    resetPassword: "Réinitialiser le mot de passe",
    sendResetLink: "Envoyer le lien",
    email: "Email",
    password: "Mot de passe",
    confirmPassword: "Confirmer le mot de passe",
  },
  nav: {
    dashboard: "Tableau de bord",
    leadFinder: "Recherche de leads",
    savedLeads: "Leads sauvegardés",
    settings: "Paramètres",
    billing: "Facturation",
    menu: "Menu",
    closeMenu: "Fermer le menu",
  },
  plan: {
    starter: "Starter",
    pro: "Pro",
    agency: "Agency",
  },
} as const;
