export const labels = {
  common: {
    save: "Enregistrer",
    cancel: "Annuler",
    delete: "Supprimer",
    edit: "Modifier",
    close: "Fermer",
    confirm: "Confirmer",
    retry: "Réessayer",
    loading: "Chargement...",
  },
  auth: {
    login: "Se connecter",
    logout: "Se déconnecter",
    signup: "Créer un compte",
    forgotPassword: "Mot de passe oublié ?",
    resetPassword: "Réinitialiser le mot de passe",
    sendResetLink: "Envoyer le lien",
    email: "Email",
    password: "Mot de passe",
    confirmPassword: "Confirmer le mot de passe",
  },
  nav: {
    dashboard: "Dashboard",
    leadFinder: "Lead Finder",
    savedLeads: "Saved Leads",
    settings: "Settings",
    billing: "Billing",
  },
  shell: {
    appName: "OutreachAI",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    userMenuLabel: "Account menu",
    planBadge: {
      starter: "Starter",
      pro: "Pro",
      agency: "Agency",
    },
    sessionError: "Session error",
    sessionErrorDescription: "Unable to load your account. Please log in again.",
  },
} as const;
