export const labels = {
  common: {
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    close: "Close",
    confirm: "Confirm",
    retry: "Retry",
    loading: "Loading...",
    or: "or",
  },
  auth: {
    login: "Sign in",
    logout: "Sign out",
    signup: "Create account",
    signingIn: "Signing in…",
    signingUp: "Creating account…",
    forgotPassword: "Forgot password?",
    resetPassword: "Reset password",
    resettingPassword: "Resetting…",
    sendResetLink: "Send reset link",
    sendingResetLink: "Sending…",
    email: "Email",
    password: "Password",
    newPassword: "New password",
    confirmPassword: "Confirm password",
    fullName: "Full name",
    loginTitle: "Welcome back",
    loginSubtitle: "Sign in to your account to continue",
    signupTitle: "Create your account",
    signupSubtitle: "Start generating leads in minutes",
    forgotTitle: "Forgot password?",
    forgotSubtitle: "Enter your email to receive a reset link",
    resetTitle: "Reset password",
    resetSubtitle: "Choose a new secure password",
    emailSentTitle: "Email sent",
    emailSentDescription: "If an account exists with that email, you'll receive a link to reset your password.",
    passwordResetTitle: "Password reset",
    passwordResetDescription: "Your password has been updated successfully.",
    backToSignIn: "Back to sign in",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    createOne: "Create one",
    signIn: "Sign in",
    termsPrefix: "By continuing, you agree to our",
    termsSignupPrefix: "By creating an account, you agree to our",
    termsLink: "Terms of Service",
    passwordMinLength: "Must be at least 8 characters",
    passwordsMismatch: "Passwords do not match",
    invalidResetLink: "Invalid or expired reset link.",
    emailPlaceholder: "you@example.com",
    passwordPlaceholder: "Enter your password",
    namePlaceholder: "John Doe",
    confirmPasswordPlaceholder: "Re-enter your password",
    newPasswordPlaceholder: "••••••••",
    rememberPassword: "Remember your password?",
  },
  nav: {
    dashboard: "Dashboard",
    leadFinder: "Lead Finder",
    savedLeads: "Saved Leads",
    settings: "Settings",
    billing: "Billing",
  },
  shell: {
    appName: "OutreachAI",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    userMenuLabel: "Account menu",
    planBadge: {
      starter: "Starter",
      pro: "Pro",
      agency: "Agency",
    },
    sessionError: "Session error",
    sessionErrorDescription: "Unable to load your account. Please log in again.",
  },
  dashboard: {
    title: "Dashboard",
    subtitle: "Your workspace overview",
    quickActions: "Quick actions",
    openLeadFinder: "Find leads",
    viewSavedLeads: "View saved leads",
    completeSetup: "Complete setup",
    openLeadFinderDescription:
      "Search by industry and location, then save the best leads.",
    viewSavedLeadsDescription:
      "Review, filter, and take action on the leads you saved.",
    completeSetupDescription:
      "Define your offer so AI outreach matches what you sell.",
    emptyTitle: "Welcome — let’s find your first leads",
    emptyDescription:
      "Start with the Lead Finder, save a few high-quality businesses, and come back here to track progress.",
    emptyCta: "Go to Lead Finder",
  },
} as const;
